services:

  qa-mariadb:
    image: mariadb:11
    container_name: qa-mariadb
    restart: always

    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

  qa-backend:
    build:
      context: ./qa_automation_backend/qa_automation_backend

    container_name: qa-backend

    depends_on:
      - qa-mariadb

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://qa-mariadb:3306/${MARIADB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MARIADB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MARIADB_PASSWORD}

volumes:
  mariadb_data: